version: "3.7"

services:
  postgres-svc:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - bec-data:/var/lib/postgresql/data

  adminer-svc:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  bec-data: